# Form implementation generated from reading ui file 'calcFace.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(356, 474)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #Clear Button
        self.buttonClear = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('C'))
        self.buttonClear.setGeometry(QtCore.QRect(10, 130, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonClear.setFont(font)
        self.buttonClear.setAutoFillBackground(False)
        self.buttonClear.setObjectName("buttonClear")
        self.buttonMode = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: MainWindow.resize(656, 474))
        self.buttonMode.setGeometry(QtCore.QRect(90, 130, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)

        #Mode Button
        self.buttonMode.setFont(font)
        self.buttonMode.setAutoFillBackground(False)
        self.buttonMode.setObjectName("buttonMode")
        self.buttonDel = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.delIt())
        self.buttonDel.setGeometry(QtCore.QRect(170, 130, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)

        #Delete Button
        self.buttonDel.setFont(font)
        self.buttonDel.setMouseTracking(False)
        self.buttonDel.setAutoFillBackground(False)
        self.buttonDel.setObjectName("buttonDel")

        #Add button
        self.buttonAdd = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('+'))
        self.buttonAdd.setGeometry(QtCore.QRect(270, 310, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonAdd.setFont(font)
        self.buttonAdd.setAutoFillBackground(False)
        self.buttonAdd.setObjectName("buttonAdd")

        #Divide Button
        self.buttonDivide = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('/'))
        self.buttonDivide.setGeometry(QtCore.QRect(270, 130, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonDivide.setFont(font)
        self.buttonDivide.setAutoFillBackground(False)
        self.buttonDivide.setObjectName("buttonDivide")

        #Button 7
        self.button7 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('7'))
        self.button7.setGeometry(QtCore.QRect(10, 190, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button7.setFont(font)
        self.button7.setAutoFillBackground(False)
        self.button7.setObjectName("button7")

        #Button 9
        self.button9 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('9'))
        self.button9.setGeometry(QtCore.QRect(170, 190, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button9.setFont(font)
        self.button9.setAutoFillBackground(False)
        self.button9.setObjectName("button9")

        #Button 8
        self.button8 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('8'))
        self.button8.setGeometry(QtCore.QRect(90, 190, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button8.setFont(font)
        self.button8.setAutoFillBackground(False)
        self.button8.setObjectName("button8")

        #Button 4
        self.button4 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('4'))
        self.button4.setGeometry(QtCore.QRect(10, 250, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button4.setFont(font)
        self.button4.setAutoFillBackground(False)
        self.button4.setObjectName("button4")

        #Button 5
        self.button5 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('5'))
        self.button5.setGeometry(QtCore.QRect(90, 250, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button5.setFont(font)
        self.button5.setAutoFillBackground(False)
        self.button5.setObjectName("button5")

        #Button Multiply
        self.buttonMultiply = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('*'))
        self.buttonMultiply.setGeometry(QtCore.QRect(270, 190, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonMultiply.setFont(font)
        self.buttonMultiply.setAutoFillBackground(False)
        self.buttonMultiply.setObjectName("buttonMultiply")

        #Button 2
        self.button2 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('2'))
        self.button2.setGeometry(QtCore.QRect(90, 310, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button2.setFont(font)
        self.button2.setAutoFillBackground(False)
        self.button2.setObjectName("button2")

        #Button 3
        self.button3 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('3'))
        self.button3.setGeometry(QtCore.QRect(170, 310, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button3.setFont(font)
        self.button3.setAutoFillBackground(False)
        self.button3.setObjectName("button3")

        #Button 6
        self.button6 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('6'))
        self.button6.setGeometry(QtCore.QRect(170, 250, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button6.setFont(font)
        self.button6.setAutoFillBackground(False)
        self.button6.setObjectName("button6")

        #Button 1
        self.button1 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('1'))
        self.button1.setGeometry(QtCore.QRect(10, 310, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button1.setFont(font)
        self.button1.setAutoFillBackground(False)
        self.button1.setObjectName("button1")

        #Button Subtract
        self.buttonSubtract = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('-'))
        self.buttonSubtract.setGeometry(QtCore.QRect(270, 250, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonSubtract.setFont(font)
        self.buttonSubtract.setAutoFillBackground(False)
        self.buttonSubtract.setObjectName("buttonSubtract")

        #Button Neg/Pos
        self.buttonNegPos = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.negPosIt())
        self.buttonNegPos.setGeometry(QtCore.QRect(10, 370, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonNegPos.setFont(font)
        self.buttonNegPos.setAutoFillBackground(False)
        self.buttonNegPos.setObjectName("buttonNegPos")

        #Button 0
        self.button0 = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.pressIt('0'))
        self.button0.setGeometry(QtCore.QRect(90, 370, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.button0.setFont(font)
        self.button0.setAutoFillBackground(False)
        self.button0.setObjectName("button0")

        #Button =
        self.buttonEqual = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.equalIt())
        self.buttonEqual.setGeometry(QtCore.QRect(270, 370, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonEqual.setFont(font)
        self.buttonEqual.setAutoFillBackground(False)
        self.buttonEqual.setObjectName("buttonEqual")

        #Button Decimal
        self.buttonDecimal = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.dotIt())
        self.buttonDecimal.setGeometry(QtCore.QRect(170, 370, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.buttonDecimal.setFont(font)
        self.buttonDecimal.setAutoFillBackground(False)
        self.buttonDecimal.setObjectName("buttonDecimal")

        #Main label
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")

        #Button Circle
        self.buttonCircle = QtWidgets.QRadioButton(parent=self.centralwidget, clicked= lambda: self.area())
        self.buttonCircle.setGeometry(QtCore.QRect(370, 20, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCircle.setFont(font)
        self.buttonCircle.setObjectName("buttonCircle")

        #Button Group
        self.areaChoice = QtWidgets.QButtonGroup(MainWindow)
        self.areaChoice.setObjectName("areaChoice")
        self.areaChoice.addButton(self.buttonCircle)

        # Button Rectangle
        self.buttonRectangle = QtWidgets.QRadioButton(parent=self.centralwidget, clicked= lambda: self.area())
        self.buttonRectangle.setGeometry(QtCore.QRect(370, 60, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRectangle.setFont(font)
        self.buttonRectangle.setObjectName("buttonRectangle")
        self.areaChoice.addButton(self.buttonRectangle)

        #Button Triangle
        self.buttonTriangle = QtWidgets.QRadioButton(parent=self.centralwidget, clicked= lambda: self.area())
        self.buttonTriangle.setGeometry(QtCore.QRect(510, 60, 82, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonTriangle.setFont(font)
        self.buttonTriangle.setObjectName("buttonTriangle")
        self.areaChoice.addButton(self.buttonTriangle)

        #Button Square
        self.buttonSquare = QtWidgets.QRadioButton(parent=self.centralwidget, clicked= lambda: self.area())
        self.buttonSquare.setGeometry(QtCore.QRect(510, 20, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonSquare.setFont(font)
        self.buttonSquare.setObjectName("buttonSquare")
        self.areaChoice.addButton(self.buttonSquare)

        #First entry
        self.entryOne = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.entryOne.setGeometry(QtCore.QRect(380, 110, 231, 20))
        self.entryOne.setPlaceholderText("Choose Option")
        self.entryOne.setObjectName("entryOne")
        self.entryOne.hide()

        #Second entry
        self.entryTwo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.entryTwo.setGeometry(QtCore.QRect(380, 140, 231, 20))
        self.entryTwo.setPlaceholderText("Choose Option")
        self.entryTwo.setObjectName("entryTwo")
        self.entryTwo.hide()

        #Button Compute
        self.buttonCompute = QtWidgets.QPushButton(parent=self.centralwidget, clicked= lambda: self.computeIt())
        self.buttonCompute.setGeometry(QtCore.QRect(400, 170, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCompute.setFont(font)
        self.buttonCompute.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        #Menubar
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        #Status Bar
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))
        self.buttonMode.setText(_translate("MainWindow", "Mode"))
        self.buttonDel.setText(_translate("MainWindow", "Delete"))
        self.buttonAdd.setText(_translate("MainWindow", "+"))
        self.buttonDivide.setText(_translate("MainWindow", "/"))
        self.button7.setText(_translate("MainWindow", "7"))
        self.button9.setText(_translate("MainWindow", "9"))
        self.button8.setText(_translate("MainWindow", "8"))
        self.button4.setText(_translate("MainWindow", "4"))
        self.button5.setText(_translate("MainWindow", "5"))
        self.buttonMultiply.setText(_translate("MainWindow", "x"))
        self.button2.setText(_translate("MainWindow", "2"))
        self.button3.setText(_translate("MainWindow", "3"))
        self.button6.setText(_translate("MainWindow", "6"))
        self.button1.setText(_translate("MainWindow", "1"))
        self.buttonSubtract.setText(_translate("MainWindow", "-"))
        self.buttonNegPos.setText(_translate("MainWindow", "+/-"))
        self.button0.setText(_translate("MainWindow", "0"))
        self.buttonEqual.setText(_translate("MainWindow", "="))
        self.buttonDecimal.setText(_translate("MainWindow", "."))
        self.label.setText(_translate("MainWindow", "0"))
        self.buttonCircle.setText(_translate("MainWindow", "Circle"))
        self.buttonRectangle.setText(_translate("MainWindow", "Rectangle"))
        self.buttonTriangle.setText(_translate("MainWindow", "Triangle"))
        self.buttonSquare.setText(_translate("MainWindow", "Square"))
        self.buttonCompute.setText(_translate("MainWindow", "Compute"))






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
